### ISSUE TITLE
Format Date

### ISSUE THREAD

**Issue by kennygokh** [ntawileh/obsidian-google-lookup#28]
Hi, is it possible to format the {{Date}} {{Time}} to a specific format like days, dd-mmm-yyyy HH:mm. I tried the templater format but it didn't work. In fact, it does not recognise templater. For example, date: <% tp.file.creation_date("YYYY-MM-DD HH:mm:ss") %>, it will just display the the same string not converting to the date format.

**Comment by ntawileh** [comment]
if you are using templater, there is a command you need to run in templater to parse the file.  I think it's called `Replace templates in active file`.  Have you tried that?

Otherwise at the moment there is no option to customize {{date}} {{time}} as provided by this plugin, but can look at that as a future enhancement

**Comment by kennygokh** [comment]
> if you are using templater, there is a command you need to run in templater to parse the file. I think it's called `Replace templates in active file`. Have you tried that?
> 
> Otherwise at the moment there is no option to customize {{date}} {{time}} as provided by this plugin, but can look at that as a future enhancement

Thanks. It works using Replace templates in active file
