### ISSUE TITLE
Unable to add account

### ISSUE THREAD

**Issue by tlazor** [ntawileh/obsidian-google-lookup#37]
Hello,

I am unable to add my account to the plugin. I created credentials for a desktop app, added my email as a test user, and I get all the way through the sign in process without any apparent error. 

The pop up in obsidian goes away and a quick bubble in the top right says "Updated authentication token for account NEW_ACCOUNT..."

Is there something I'm missing?

**Comment by ntawileh** [comment]
Hi,

- is this an organization account that might have any restrictions on using third part apps?
- Does anything show up in Settings under accounts?  
- What happens after that if you try to use any of the plugin commands? (fetch calendar or contacts)
- Have you tried deleting the accounts that show up under Plugin Settings and trying again?

**Comment by tlazor** [comment]
- No, this is a personal google account.
- No accounts show up in the settings.
- None of the commands appear.
- Reinstall doesn't seem to change anything.
- I'm using version 1.4.0 of the plugin with 1.3.5 of Obsidian

**Comment by ntawileh** [comment]
Does any error or any message show up in the console when you are adding the account?  You can open the console in Obsidian by pressing Ctrl+Shift+I in Windows and Linux, or Cmd-Option-I on macOS.

**Comment by tlazor** [comment]
Aha, I see this error in the console:
`unable to query authenticated user: People API has not been used in project XXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/people.googleapis.com/overview?project=XXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.`

Visiting that URL I enabled the People API and then was able to add an account.

Unfortunately, now I am seeing
`unable to query directory: Must be a G Suite domain user.` whenever I try and use a command like insert contact.

**Comment by ntawileh** [comment]
it works with gmail as well.  Even though you see this G Suite error in console, it should still work.  There are two calls that the plugin makes, because Google treats the two sets of contacts differently.

1. Search contacts.  The equivalent network query that you should see in the dev console under network would be to `https://people.googleapis.com/v1/people:searchContacts`.  I expect that one to work fine
2. Search directory.  That would be this endpoint: `https://people.googleapis.com/v1/people:searchDirectoryPeople`. This one is G Suite specific and will search a corporate directory for that gsuite organization.  I expect that one to fail for gmail.com because it's not applicable.  It should not, however, affect the results of (1) above.  I'll probably silence this error as an improvement for gmail accounts so people don't get confused by it

So, leaving this error aside, you are not getting any results when you search?  Are you able to find the `people:searchContacts` call in the Network tab in the console and see what results, if any, that is returning?

**Comment by tlazor** [comment]
It all looks to be working now! I needed to also enable the Calendar API, but now I can insert events and contacts. Thanks for working through the issue with me!
