### ISSUE TITLE
Event Attendees - List by name?

### ISSUE THREAD

**Issue by jnsgruk** [ntawileh/obsidian-google-lookup#8]
Hi,

Super plugin, thank you! Is it possible to create a template field that gives a comma seperated list of attendees *by name*, rather than by email address where that info is available?

I tend to have notes about people, and populate attendee information in a Dataview field like: `[[Joe Bloggs]]` - it would be great if this could support that workflow.

Many thanks!

**Comment by ntawileh** [comment]
hey thanks for the feedback!
possible, but the google API doesn't always return the attendees' display names.  depends on I think on calendar share settings but I don't know for sure yet.  
in a case where some of the attendees come back with a name, would an additional template field that shows name if it exists, otherwise email, work for your workflow? So..

{{attendees}} (exists now) would return `stewie@example.com, peter@example.com, lois@example.com`

{{attendees.name}} would potentially return `Stewie Griffin, peter@example.com, Lois Griffin`

both would also have status indicators appended, so if Stewie declined the meeting, it would be `Stewie Griffin (x), peter@example.com, Lois Griffin`

would something like that work?

**Comment by jnsgruk** [comment]
Sure, I think that would be a pretty great compromise, thanks! :)
